// import Hapi from '@hapi/hapi'
// import Joi, { required } from 'joi'
// import Boom, { boomify } from '@hapi/boom'
// import { API_AUTH_STATEGY } from './auth'
// import { UserRole } from '@prisma/client'
// import { isTeacherOfCourseOrAdmin } from '../auth-helpers'
